[build]
builder = "nixpacks"

[build.buildCommand]
commands = [
  "npm install",
  "cd client && npm install",
  "cd ../server && npm install",
  "cd .. && npm run build"
]

[build.startCommand]
command = "npm start"
